### ISSUE TITLE
Documentation for k8s_nodepool is incorrect

### ISSUE THREAD

**Issue by attrib** [ionos-cloud/module-ansible#137]
## Description
https://github.com/ionos-cloud/module-ansible/blob/master/docs/api/managed-kubernetes/k8s_nodepool.md

State the module name is k8s_nodepools
```
- name: Create k8s cluster nodepool
    k8s_nodepools:
```

It should be k8s_nodepool (without s!)

## Expected behavior
Documentation should match module.

**Comment by rmocanu-ionos** [comment]
This should be solved in 7.4.1, please let us know if there are other issues.
