### ISSUE TITLE
Server modul failure

### ISSUE THREAD

**Issue by gyokiss** [ionos-cloud/module-ansible#15]
## Description
The server modul deploys the required server but throws an error:

"msg": "failed to set instance state: 'Server' object has no attribute 'update'"

## Expected behavior

clean ansible finish

## Environment

Ansible version:

ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules/ionos-module-ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Module version: 
5.0.5

OS: 
centos 7

## Error and Debug Output
The full traceback is:

Traceback (most recent call last):
  File "/tmp/ansible_server_payload_Lx6hem/ansible_server_payload.zip/ansible/modules/server.py", line 908, in main
  File "/tmp/ansible_server_payload_Lx6hem/ansible_server_payload.zip/ansible/modules/server.py", line 567, in create_virtual_machine
AttributeError: 'Server' object has no attribute 'update'

**Comment by jbuchhammer** [comment]
Please test with Python 3.5+ too - maybe it's the same reason as in https://github.com/ionos-cloud/module-ansible/issues/16

**Comment by gyokiss** [comment]
HI, 

Ok I missed the python part. Sorry :)  Now It is installed: 
sad to say not too much things changed ( also for #16 valid) 

There is any ansible version minimum requirement?

ansible and python versions: 
ansible-playbook 2.9.27
  config file = None
  configured module search path = ['/usr/share/ansible/plugins/modules/ionos-module-ansible']
  ansible python module location = /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ansible
  executable location = /opt/rh/rh-python38/root/usr/local/bin/ansible-playbook
  python version = 3.8.11 (default, Sep  1 2021, 12:33:46) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
No config file found; using defaults


the server deployment: 

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_server_payload_7b_gfje7/ansible_server_payload.zip/ansible/modules/server.py", line 908, in main
  File "/tmp/ansible_server_payload_7b_gfje7/ansible_server_payload.zip/ansible/modules/server.py", line 567, in create_virtual_machine
AttributeError: 'Server' object has no attribute 'update'
....
  "msg": "failed to set instance state: 'Server' object has no attribute 'update'"
probably this is the reason why volume cannot attach to it:

volume create traceback:

The full traceback is:
  File "/tmp/ansible_volume_payload_6zqb1o_c/ansible_volume_payload.zip/ansible/modules/volume.py", line 579, in _attach_volume
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/api/server_api.py", line 3131, in datacenters_servers_volumes_post
    return self.datacenters_servers_volumes_post_with_http_info(datacenter_id, server_id, volume, **kwargs)  # noqa: E501
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/api/server_api.py", line 3263, in datacenters_servers_volumes_post_with_http_info
    return self.api_client.call_api(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/api_client.py", line 452, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/api_client.py", line 271, in __call_api
    raise e
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/api_client.py", line 245, in __call_api
    raise response_error
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/api_client.py", line 223, in __call_api
    response_data = self.request(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/api_client.py", line 496, in request
    return self.rest_client.POST(url,
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/rest.py", line 265, in POST
    return self.request("POST", url,
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ionoscloud/rest.py", line 224, in request
    raise ApiException(http_resp=r)

and error message: 
    "msg": "failed to attach volume: (404)\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({'Date': 'Thu, 04 Nov 2021 22:26:27 GMT', 'Server': 'Apache/2.4.38 (Debian)', 'Content-Length': '118', 'Content-Type': 'application/json', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*', 'Access-Control-Expose-Headers': '*', 'Access-Control-Allow-Methods': '*', 'Access-Control-Allow-Credentials': 'true'})\nHTTP response body: {\n  \"httpStatus\" : 404,\n  \"messages\" : [ {\n    \"errorCode\" : \"309\",\n    \"message\" : \"Resource does not exist\"\n  } ]\n}\n\n"
}

Can you direct me for next step?

Thanks
György

**Comment by gyokiss** [comment]
Hi, 

I have found out: if I leave out the lan from my plyabook, than the server part is fine. 
From traceback Ihave pointed out this part: 

--- snip --- 
        create_response = _create_machine(module, client, str(datacenter_id), name)
        changed = True
        nics = nic_server.datacenters_servers_nics_get(datacenter_id=datacenter_id, server_id=create_response.id,
                                                       depth=2)
        for n in nics.items:
            if lan == n.properties.lan:
                **_create_response.update({'public_ip': n.properties.ips[0]})_**
        virtual_machines.append(create_response)

--- snip --- 

snippet of playbook: 
``
  - name: Provision a server
    server:
       datacenter: "{{ datacenter }}"
       name: "{{ servername }}"
       auto_increment: true
       cores: 2
       ram: 4096
       availability_zone: ZONE_1
       volume_availability_zone: ZONE_1
       volume_size: 20
       cpu_family: INTEL_XEON
       disk_type: HDD
       image: "{{ image }}"
       image_password: "{{ password }}"
       ssh_keys:
           - "{{ ssh_public_key }}"
       location: "{{ location }}"
       count: 1
      **_lan: x_** -- is removed for successful run
       nat: false
      **_nic_ips: "x.x.x.x_**" --is removed for successful run
       assign_public_ip: false
       remove_boot_volume: true
       username: 
       password: 
       wait: true
       wait_timeout: "{{ timeout }}"
       state: present
    register: outputblock
    environment: "{{ proxy_env }}"
    ignore_errors: yes

**Comment by jbuchhammer** [comment]
FYI: I used the following versions
```
*    Debian 9 (2021-02)
*    Ansible 2.10.7 / ansible-base 2.10.5 (via pip)
*    Python 3.5.3
```
and had no such issues.

Anyway your issue needs some investigation.
First question: When you created the Server with LAN, was the Lan part of the playbook and created before? - Just an idea

**Comment by hkicsi** [comment]
Hi,

The lan is created before ( planned process: add now server into existing LAN) 
 the Ansible I have installed via pip

Which ionoscloud modules do you use? 

Thanks
György

**Comment by gyokiss** [comment]
I have upgraded ansible
The python traceback still there: 

Traceback (most recent call last):
  File "/tmp/ansible_server_payload_lvfpk9fy/ansible_server_payload.zip/ansible/                         modules/server.py", line 908, in main
  File "/tmp/ansible_server_payload_lvfpk9fy/ansible_server_payload.zip/ansible/                         modules/server.py", line 567, in create_virtual_machine
AttributeError: 'Server' object has no attribute 'update'

ansible 2.10.15
  config file = None
  configured module search path = ['/usr/share/ansible/plugins/modules/ionos-module-ansible']
  ansible python module location = /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ansible
  executable location = /opt/rh/rh-python38/root/usr/local/bin/ansible
  python version = 3.8.11 (default, Sep  1 2021, 12:33:46) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

$ pip list
Package         Version
--------------- ---------
ansible         2.10.7
ansible-base    2.10.15
certifi         2021.10.8
cffi            1.15.0
cryptography    35.0.0
ionoscloud      5.0.5
Jinja2          3.0.2
MarkupSafe      2.0.1
packaging       21.2
pip             19.3.1
pycparser       2.20
pyparsing       2.4.7
python-dateutil 2.8.2
PyYAML          6.0
setuptools      41.6.0
six             1.16.0
urllib3         1.26.7

**Comment by gyokiss** [comment]
Hi, now I´m pretty sure, that next 3 lines are causing my issue:

        for n in nics.items:
            if lan == n.properties.lan:
                create_response.update({'public_ip': n.properties.ips[0]}

If I comment this 3 lines out, my process runs without failure... Only I dont see, what for is here there, what I causing if I take  that away...
