### ISSUE TITLE
Support check mode in user module

### ISSUE THREAD

**Issue by jplitza** [ionos-cloud/module-ansible#202]
### Current SDK Version

```
7.4.1
```

### Use-cases

- When developing Ansible playbooks for existing infrastructure, it would be nice to test against the existing infrastructure without actually changing it.
- When executing Ansible playbooks, it would be nice to know it advance what changes.

### Proposal

Skip the actually API call that updates/creates the user when check mode is enabled. When it already existed, subsequent tasks might even succeed with the information that is returned.

**Comment by genofire** [comment]
Oh yea, a sandbox ionos api or so would be nice:

**Comment by rmocanu-ionos** [comment]
Hello, this should be available in the latest beta release, v7.5.0-beta.1, please let us if we should make any changes to the current implementation

**Comment by jplitza** [comment]
@rmocanu-ionos Thanks for the quick implementation! I love that you implemented diff mode along the way!

However, check mode doesn't return the object itself, even if some of the keys are known. When the user already exists, I would love the `user` key of the response to contain the fields the module expects to be set after its invocation (so basically what is used during the diff computation as `after`, plus the UUID identifier as `id`).

**Comment by rmocanu-ionos** [comment]
Hello, I have included the changes in the latest release, v7.5.0, please let us know if there are any other problems
