### ISSUE TITLE
volume list for a specific server

### ISSUE THREAD

**Issue by gyokiss** [ionos-cloud/module-ansible#23]
### Current SDK Version
5.0.5

### Use-cases
For update a volume ( name, size, etc) have a list of attached volumes.

**Comment by jbuchhammer** [comment]
Hi @gyokiss ,

as stated in #22 : If you want to update a specific volume, you already have to know which one by name or UUID.
So, how do you want to perform this by having a list only?

And bare with me if I'm totally misled by my thoughts.

**Comment by hkicsi** [comment]
Here I would like to update the name of specific volume: 
I create a centos from ionos image, and the boot vol name I have to change to a specific name - following our naming convention. 
The way I have found, through direct API call, I have to filter out the UUID,  than I can call up the volume module. Here the main issue - I have also change the volume size also - the name change is not enough for module.

gyokiss

**Comment by avirtopeanu-ionos** [comment]
Hello,  A new module has been added: `volume-info`, on the [v6.2.0](https://galaxy.ansible.com/ionoscloudsdk/ionoscloud) release. Sadly, we are no longer adding new features or enhancements on version 5, we're addressing only bugs. We encourage you to update the module to version 6.

Have a nice day!
