### ISSUE TITLE
docs and tests of this repository

### ISSUE THREAD

**Issue by rdxmb** [ionos-cloud/module-ansible#60]
Hello,

after debugging and researching for https://github.com/ionos-cloud/module-ansible/pull/59 for some hours I've just found the tests in https://github.com/ionos-cloud/module-ansible/blob/master/tests/k8s-cluster-nodepool-test.yml , which seems do be the better documentation for me :+1: :laughing: 

Would it be a solution to match these folders - either with symlinks or running `include_tasks` or something like that? So there would be a single source of truth ;)

**Comment by mihaela-mh** [comment]
Hello! Thank you for raising this issue!

Indeed, a single source of truth will add more clarity to the documentation. We're now working on some refactoring on the documentation part and we'll take care of this too. Will keep you updated here with the status of this enhancement.

Have a nice day!
