### ISSUE TITLE
Token Authentication

### ISSUE THREAD

**Issue by detmoo** [ionos-cloud/module-ansible#63]
### Current SDK Version

```
5.0.7
```

### Use-cases

Secure authentication for the Ionos Ansible Module

### Attempted Solutions

Invoke an Ansible Playbook where variable IONOS_TOKEN is defined in the environment but variables IONOS_USERNAME and IONOS_PASSWORD are not defined. As to be expected given the relevant section in the docs, we encounter a fatal error with '''"msg": "missing required arguments: password, username"'''

### Proposal

To be consistent with methods for secure authentication upon direct usage of the Ionoscloud Python SDK, we propose the Ansible Module should also authenticate when environment variable IONOS_TOKEN exposes a valid Auth Token string - and this should be the priority method so that, only in the event IONOS_TOKEN is not set, then the Ansible Module can/should revert to look for IONOS_USERNAME and IONOS_PASSWORD. 

IMO this update would be preferable since (i) less requirement to propagate user secrets across devices (ii) to adopt a consistent authentication methodology.

### References

Ansible Module Authentication: https://docs.ionos.com/ansible/usage/authentication

Python SDK Authentication: https://docs.ionos.com/python-sdk/#authentication

**Comment by avirtopeanu-ionos** [comment]
Hello! Token authentication is now possible with [the new 6.1.3 release](https://galaxy.ansible.com/ionoscloudsdk/ionoscloud). You can view the changelog here: https://docs.ionos.com/ansible/changelog. There will also be a v5 release soon which will include this feature.

Have a nice day!
