### ISSUE TITLE
Invalid nat property for server

### ISSUE THREAD

**Issue by jbuchhammer** [ionos-cloud/module-ansible#9]
## Description
Documentation and code in module v5.0.2 of Server contain references to a _nat_ property which would allow to connect a private NIC to the public. This is not supported by API v5 but an upcoming feature for Module v6.x.y / API v6.

## Expected behavior
non-existant API features are not present in documentation and code 

## Environment

Module version: 
```
v5.0.2
```

**Comment by mihaela-mh** [comment]
Hello! [We released a new version, 6.1.3](https://galaxy.ansible.com/ionoscloudsdk/ionoscloud) with a fix for this issue. Thanks for flagging it!

Have a nice day
